### ISSUE TITLE
extra  " ], " causes json to not be parsed

### ISSUE THREAD

**Issue by exno** [jamf/HealthCheckUtility#2]
**Version:** Release Beta 2 -  v1.0-beta.2 commit 26bccd7
**Replicable:** Yes, tested 3 different environments

**Issue:**
I have tried on three different jamf servers (one test and 2 production) to run the healthcheck headless.

right after the array for "scripts_needing_update", an extra closing bracket is placed resulting in a section that looks like this: 

		"scripts_needing_update": [{
			"name": "someScript.sh"
		}, {
			"name": "AwesomeScript.sh"
		}, {
			"name": "RunMe.py"
		}],
	],
	"password_strength": {

the " ], " is unpaired and a matching one further up in the code doesn't seem to make sense. 

I used jsonlint.com to find the error and fix it, then used http://www.jsoneditoronline.org/ to verify it parses after that. So i have a workaround but wanted to share the issue in case others are seeing it too.

**Comment by iamjake648** [comment]
I have added better exception handling for when the XML from the JSS can not be parsed with JDOM. This should eliminate this happening again. The extra bracket was produced when the JDOM error was not handled properly due to a special character. 

This is a **great workaround** for all cases where the JSON fails to be parsed.
